name: Deploy GH Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_ONLY: true
      - name: upload
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: public/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
